'use strict';
let 
// Статистика
statsHome = {
	goals: 0,
	shots: 0,
	shots_on_goals: 0,
	possession: 0,
	passes: 0,
	crosses: 0,
	free_kicks: 0,
	corners: 0,
	fouls: 0,
	yellow_cards: 0,
	red_cards: 0,
	tackles: 0,
	dribbles: 0,
	offsides: 0
},
statsAway = {
	goals: 0,
	shots: 0,
	shots_on_goals: 0,
	possession: 0,
	passes: 0,
	crosses: 0,
	free_kicks: 0,
	corners: 0,
	fouls: 0,
	yellow_cards: 0,
	red_cards: 0,
	tackles: 0,
	dribbles: 0,
	offsides: 0
},
// Juventus
club1 = {
	id: 1,
	name: 'Juventus',
	kitColor: ['#000', '#FFF', '#000'],
	nextMatch: 'home',
	squad: [
		{
			id: 1,
			name: 'Gianluigi',
			surname: 'Buffon',
			amplua: 'GK',
			number: 1,
			rost: 190,
			ves: 80,
			skils: {
			aggression: 0,
			anticipation: 17,
			bravery: 20,
			composure: 18,
			concentration: 19,
			decisions: 19,
			finishing: 3,
			flair: 0,
			of_the_ball: 0,
			positioning: 18,
			work_rate: 15,
			acceleration: 13,
			jumping: 17,
			pace: 11,
			stamina: 15,
			strength: 16,
			corners: 0,
			crossing: 0,
			dribbling: 0,
			first_touch: 8,
			free_kicks: 0,
			heading: 0,
			long_shots: 0,
			long_throws: 0,
			marking: 0,
			passing: 0,
			penalty: 0,
			tackling: 0,
			technique: 7,
			udar: 5
		}
		},
		{
			id: 2,
			name: 'Nicola',
			surname: 'Legrottaglie',
			amplua: 'DC',
			number: 30,
			rost: 185,
			ves: 73,
			skils: {
			aggression: 15,
			anticipation: 8,
			bravery: 15,
			composure: 10,
			concentration: 5,
			decisions: 10,
			finishing: 7,
			flair: 7,
			of_the_ball: 14,
			positioning: 14,
			work_rate: 14,
			acceleration: 12,
			jumping: 17,
			pace: 15,
			stamina: 12,
			strength: 13,
			corners: 5,
			crossing: 7,
			dribbling: 9,
			first_touch: 12,
			free_kicks: 5,
			heading: 17,
			long_shots: 5,
			long_throws: 10,
			marking: 13,
			passing: 13,
			penalty: 4,
			tackling: 12,
			technique: 8,
			udar: 7
		}
		},
		{
			id: 3,
			name: 'Igor',
			surname: 'Tudor',
			amplua: 'DC',
			number: 3,
			rost: 193,
			ves: 90,
			skils: {
			aggression: 14,
			anticipation: 11,
			bravery: 14,
			composure: 13,
			concentration: 9,
			decisions: 15,
			finishing: 7,
			flair: 9,
			of_the_ball: 8,
			positioning: 15,
			work_rate: 13,
			acceleration: 9,
			jumping: 17,
			pace: 11,
			stamina: 15,
			strength: 18,
			corners: 5,
			crossing: 11,
			dribbling: 7,
			first_touch: 13,
			free_kicks: 7,
			heading: 18,
			long_shots: 11,
			long_throws: 9,
			marking: 16,
			passing: 13,
			penalty: 12,
			tackling: 16,
			technique: 12,
			udar: 7
		}
		},
		{
			id: 4,
			name: 'Giorgio',
			surname: 'Chiellini',
			amplua: 'DC',
			number: 5,
			rost: 186,
			ves: 76,
			skils: {
			aggression: 14,
			anticipation: 16,
			bravery: 13,
			composure: 11,
			concentration: 14,
			decisions: 12,
			finishing: 7,
			flair: 10,
			of_the_ball: 16,
			positioning: 14,
			work_rate: 15,
			acceleration: 13,
			jumping: 15,
			pace: 17,
			stamina: 16,
			strength: 16,
			corners: 12,
			crossing: 17,
			dribbling: 11,
			first_touch: 11,
			free_kicks: 10,
			heading: 14,
			long_shots: 12,
			long_throws: 18,
			marking: 13,
			passing: 14,
			penalty: 0,
			tackling: 14,
			technique: 12,
			udar: 8
		}
		},
		{
			id: 5,
			name: 'Alessandro',
			surname: 'Birindelli',
			amplua: 'DR',
			number: 2,
			rost: 176,
			ves: 73,
			skils: {
			aggression: 10,
			anticipation: 10,
			bravery: 9,
			composure: 15,
			concentration: 14,
			decisions: 11,
			finishing: 8,
			flair: 8,
			of_the_ball: 11,
			positioning: 13,
			work_rate: 13,
			acceleration: 17,
			jumping: 10,
			pace: 14,
			stamina: 14,
			strength: 11,
			corners: 8,
			crossing: 17,
			dribbling: 8,
			first_touch: 6,
			free_kicks: 16,
			heading: 6,
			long_shots: 16,
			long_throws: 10,
			marking: 10,
			passing: 12,
			penalty: 14,
			tackling: 14,
			technique: 12,
			udar: 9
		}
		},
		{
			id: 6,
			name: 'Pavel',
			surname: 'Nedved',
			amplua: 'ML',
			number: 11,
			rost: 177,
			ves: 70,
			skils: {
			aggression: 16,
			anticipation: 17,
			bravery: 20,
			composure: 16,
			concentration: 17,
			decisions: 14,
			finishing: 16,
			flair: 13,
			of_the_ball: 18,
			positioning: 12,
			work_rate: 16,
			acceleration: 16,
			jumping: 10,
			pace: 12,
			stamina: 17,
			strength: 16,
			corners: 12,
			crossing: 15,
			dribbling: 12,
			first_touch: 15,
			free_kicks: 16,
			heading: 14,
			long_shots: 17,
			long_throws: 6,
			marking: 7,
			passing: 16,
			penalty: 15,
			tackling: 12,
			technique: 16,
			udar: 17
		}
		},
		{
			id: 7,
			name: 'Claudio',
			surname: 'Marchisio',
			amplua: 'MC',
			number: 15,
			rost: 0,
			ves: 0,
			skils: {
			aggression: 0,
			anticipation: 0,
			bravery: 0,
			composure: 0,
			concentration: 0,
			decisions: 0,
			finishing: 12,
			flair: 0,
			of_the_ball: 0,
			positioning: 0,
			work_rate: 0,
			acceleration: 0,
			jumping: 0,
			pace: 0,
			stamina: 0,
			strength: 0,
			corners: 0,
			crossing: 0,
			dribbling: 0,
			first_touch: 0,
			free_kicks: 0,
			heading: 0,
			long_shots: 0,
			long_throws: 0,
			marking: 0,
			passing: 16,
			penalty: 0,
			tackling: 13,
			technique: 0,
			udar: 14
		}
		},
		{
			id: 8,
			name: 'Alessio',
			surname: 'Tacchinardi',
			amplua: 'MC',
			number: 7,
			rost: 187,
			ves: 80,
			skils: {
			aggression: 18,
			anticipation: 15,
			bravery: 15,
			composure: 15,
			concentration: 13,
			decisions: 14,
			finishing: 11,
			flair: 8,
			of_the_ball: 12,
			positioning: 16,
			work_rate: 15,
			acceleration: 13,
			jumping: 15,
			pace: 10,
			stamina: 17,
			strength: 15,
			corners: 6,
			crossing: 11,
			dribbling: 10,
			first_touch: 14,
			free_kicks: 12,
			heading: 15,
			long_shots: 15,
			long_throws: 8,
			marking: 15,
			passing: 14,
			penalty: 14,
			tackling: 15,
			technique: 12,
			udar: 14
		}
		},
		{
			id: 9,
			name: 'Mauro',
			surname: 'Camoranesi',
			amplua: 'MR',
			number: 16,
			rost: 177,
			ves: 70,
			skils: {
			aggression: 14,
			anticipation: 13,
			bravery: 15,
			composure: 13,
			concentration: 12,
			decisions: 13,
			finishing: 15,
			flair: 16,
			of_the_ball: 16,
			positioning: 13,
			work_rate: 14,
			acceleration: 16,
			jumping: 15,
			pace: 14,
			stamina: 13,
			strength: 13,
			corners: 13,
			crossing: 18,
			dribbling: 17,
			first_touch: 17,
			free_kicks: 12,
			heading: 15,
			long_shots: 10,
			long_throws: 8,
			marking: 7,
			passing: 16,
			penalty: 14,
			tackling: 11,
			technique: 17,
			udar: 16
		}
		},
		{
			id: 10,
			name: 'Alessandro',
			surname: 'Del Piero',
			amplua: 'FC',
			number: 10,
			rost: 173,
			ves: 73,
			skils: {
			aggression: 13,
			anticipation: 14,
			bravery: 11,
			composure: 17,
			concentration: 12,
			decisions: 15,
			finishing: 17,
			flair: 16,
			of_the_ball: 16,
			positioning: 9,
			work_rate: 16,
			acceleration: 14,
			jumping: 13,
			pace: 14,
			stamina: 13,
			strength: 14,
			corners: 14,
			crossing: 15,
			dribbling: 15,
			first_touch: 15,
			free_kicks: 17,
			heading: 14,
			long_shots: 14,
			long_throws: 8,
			marking: 6,
			passing: 16,
			penalty: 20,
			tackling: 7,
			technique: 18,
			udar: 18
		}
		},
		{
			id: 11,
			name: 'David',
			surname: 'Trezeguet',
			amplua: 'SC',
			number: 17,
			rost: 190,
			ves: 80,
			skils: {
			aggression: 13,
			anticipation: 17,
			bravery: 15,
			composure: 18,
			concentration: 17,
			decisions: 17,
			finishing: 20,
			flair: 12,
			of_the_ball: 19,
			positioning: 5,
			work_rate: 13,
			acceleration: 12,
			jumping: 17,
			pace: 12,
			stamina: 15,
			strength: 15,
			corners: 5,
			crossing: 8,
			dribbling: 10,
			first_touch: 16,
			free_kicks: 7,
			heading: 19,
			long_shots: 13,
			long_throws: 6,
			marking: 5,
			passing: 12,
			penalty: 13,
			tackling: 6,
			technique: 13,
			udar: 15
		}
		}
	]
},
// Fiorentina
club2 = {
	id: 2,
	name: 'Fiorentina',
	kitColor: ['#FFF', '#7E57C2', '#FFF'],
	nextMatch: 'away',
	squad: [
		{
			id: 13,
			name: 'Sébastien',
			surname: 'Frey',
			amplua: 'GK',
			number: 1,
			rost: 189,
			ves: 85,
			skils: {
			aggression: 16,
			anticipation: 16,
			bravery: 15,
			composure: 20,
			concentration: 14,
			decisions: 15,
			finishing: 3,
			flair: 5,
			of_the_ball: 5,
			positioning: 13,
			work_rate: 13,
			acceleration: 16,
			jumping: 17,
			pace: 15,
			stamina: 16,
			strength: 16,
			corners: 2,
			crossing: 6,
			dribbling: 5,
			first_touch: 0,
			free_kicks: 6,
			heading: 16,
			long_shots: 11,
			long_throws: 0,
			marking: 12,
			passing: 12,
			penalty: 9,
			tackling: 12,
			technique: 19,
			udar: 5
		}
		},
		{
			id: 15,
			name: 'Manuel',
			surname: 'Pasqual',
			amplua: 'DL',
			number: 23,
			rost: 178,
			ves: 70,
			skils: {
			aggression: 13,
			anticipation: 12,
			bravery: 12,
			composure: 13,
			concentration: 10,
			decisions: 11,
			finishing: 6,
			flair: 7,
			of_the_ball: 14,
			positioning: 12,
			work_rate: 10,
			acceleration: 15,
			jumping: 10,
			pace: 18,
			stamina: 16,
			strength: 12,
			corners: 14,
			crossing: 18,
			dribbling: 12,
			first_touch: 11,
			free_kicks: 12,
			heading: 10,
			long_shots: 10,
			long_throws: 11,
			marking: 14,
			passing: 12,
			penalty: 15,
			tackling: 13,
			technique: 14,
			udar: 8
		}
		},
		{
			id: 19,
			name: 'Per',
			surname: 'Krøldrup',
			amplua: 'DC',
			number: 2,
			rost: 194,
			ves: 82,
			skils: {
			aggression: 15,
			anticipation: 15,
			bravery: 15,
			composure: 12,
			concentration: 13,
			decisions: 12,
			finishing: 6,
			flair: 5,
			of_the_ball: 9,
			positioning: 14,
			work_rate: 15,
			acceleration: 12,
			jumping: 16,
			pace: 11,
			stamina: 16,
			strength: 16,
			corners: 5,
			crossing: 6,
			dribbling: 9,
			first_touch: 8,
			free_kicks: 6,
			heading: 16,
			long_shots: 8,
			long_throws: 12,
			marking: 14,
			passing: 9,
			penalty: 0,
			tackling: 15,
			technique: 12,
			udar: 6
		}
		},
		{
			id: 20,
			name: 'Alessandro',
			surname: 'Gamberini',
			amplua: 'DC',
			number: 5,
			rost: 185,
			ves: 78,
			skils: {
			aggression: 16,
			anticipation: 15,
			bravery: 17,
			composure: 15,
			concentration: 13,
			decisions: 13,
			finishing: 7,
			flair: 3,
			of_the_ball: 4,
			positioning: 15,
			work_rate: 15,
			acceleration: 12,
			jumping: 13,
			pace: 13,
			stamina: 15,
			strength: 11,
			corners: 2,
			crossing: 5,
			dribbling: 7,
			first_touch: 8,
			free_kicks: 5,
			heading: 13,
			long_shots: 0,
			long_throws: 0,
			marking: 16,
			passing: 9,
			penalty: 0,
			tackling: 14,
			technique: 7,
			udar: 8
		}
		},
		{
			id: 14,
			name: 'Tomas',
			surname: 'Ujfalusi',
			amplua: 'DR',
			number: 21,
			rost: 185,
			ves: 76,
			skils: {
			aggression: 16,
			anticipation: 17,
			bravery: 16,
			composure: 16,
			concentration: 16,
			decisions: 17,
			finishing: 8,
			flair: 8,
			of_the_ball: 8,
			positioning: 16,
			work_rate: 15,
			acceleration: 14,
			jumping: 17,
			pace: 15,
			stamina: 18,
			strength: 16,
			corners: 8,
			crossing: 11,
			dribbling: 9,
			first_touch: 14,
			free_kicks: 7,
			heading: 15,
			long_shots: 8,
			long_throws: 10,
			marking: 16,
			passing: 13,
			penalty: 11,
			tackling: 17,
			technique: 11,
			udar: 8
		}
		},
		{
			id: 17,
			name: 'Martin',
			surname: 'Jørgensen',
			amplua: 'AML',
			number: 20,
			rost: 179,
			ves: 75,
			skils: {
			aggression: 8,
			anticipation: 12,
			bravery: 5,
			composure: 14,
			concentration: 14,
			decisions: 16,
			finishing: 13,
			flair: 15,
			of_the_ball: 15,
			positioning: 13,
			work_rate: 12,
			acceleration: 14,
			jumping: 8,
			pace: 13,
			stamina: 10,
			strength: 7,
			corners: 15,
			crossing: 16,
			dribbling: 15,
			first_touch: 15,
			free_kicks: 12,
			heading: 11,
			long_shots: 14,
			long_throws: 6,
			marking: 7,
			passing: 15,
			penalty: 14,
			tackling: 8,
			technique: 17,
			udar: 15
		}
		},
		{
			id: 16,
			name: 'Fabio',
			surname: 'Liverani',
			amplua: 'MC',
			number: 11,
			rost: 175,
			ves: 72,
			skils: {
			aggression: 12,
			anticipation: 15,
			bravery: 12,
			composure: 15,
			concentration: 15,
			decisions: 18,
			finishing: 11,
			flair: 14,
			of_the_ball: 12,
			positioning: 10,
			work_rate: 14,
			acceleration: 9,
			jumping: 7,
			pace: 10,
			stamina: 16,
			strength: 10,
			corners: 11,
			crossing: 10,
			dribbling: 15,
			first_touch: 18,
			free_kicks: 13,
			heading: 7,
			long_shots: 15,
			long_throws: 0,
			marking: 9,
			passing: 18,
			penalty: 16,
			tackling: 10,
			technique: 17,
			udar: 13
		}
		},
		{
			id: 18,
			name: 'Riccardo',
			surname: 'Montolivo',
			amplua: 'MC',
			number: 18,
			rost: 181,
			ves: 65,
			skils: {
			aggression: 13,
			anticipation: 15,
			bravery: 12,
			composure: 12,
			concentration: 14,
			decisions: 12,
			finishing: 13,
			flair: 19,
			of_the_ball: 12,
			positioning: 9,
			work_rate: 14,
			acceleration: 13,
			jumping: 9,
			pace: 13,
			stamina: 15,
			strength: 10,
			corners: 16,
			crossing: 15,
			dribbling: 17,
			first_touch: 17,
			free_kicks: 14,
			heading: 5,
			long_shots: 13,
			long_throws: 12,
			marking: 7,
			passing: 15,
			penalty: 17,
			tackling: 8,
			technique: 18,
			udar: 15
		}
		},
		{
			id: 12,
			name: 'Adrian',
			surname: 'Mutu',
			amplua: 'AMR',
			number: 10,
			rost: 180,
			ves: 74,
			skils: {
				aggression: 13,
				anticipation: 14,
				bravery: 12,
				composure: 15,
				concentration: 11,
				decisions: 12,
				finishing: 16,
				flair: 17,
				of_the_ball: 16,
				positioning: 11,
				work_rate: 13,
				acceleration: 15,
				jumping: 11,
				pace: 15,
				stamina: 14,
				strength: 11,
				corners: 13,
				crossing: 14,
				dribbling: 16,
				first_touch: 14,
				free_kicks: 15,
				heading: 7,
				long_shots: 16,
				long_throws: 9,
				marking: 4,
				passing: 16,
				penalty: 17,
				tackling: 10,
				technique: 17,
				udar: 17
			}
		},
		{
			id: 11,
			name: 'Luca',
			surname: 'Toni',
			amplua: 'FC',
			number: 30,
			rost: 194,
			ves: 88,
			skils: {
				aggression: 15,
				anticipation: 18,
				bravery: 17,
				composure: 15,
				concentration: 18,
				decisions: 16,
				finishing: 20,
				flair: 9,
				of_the_ball: 20,
				positioning: 12,
				work_rate: 15,
				acceleration: 14,
				jumping: 19,
				pace: 15,
				stamina: 16,
				strength: 20,
				corners: 4,
				crossing: 8,
				dribbling: 15,
				first_touch: 15,
				free_kicks: 5,
				heading: 18,
				long_shots: 13,
				long_throws: 2,
				marking: 12,
				passing: 15,
				penalty: 13,
				tackling: 11,
				technique: 14,
				udar: 13
			}
		},
		{
			id: 21,
			name: 'Gianpaolo',
			surname: 'Pazzini',
			amplua: 'FC',
			startSostav: 'F CL',
			number: 29,
			rost: 180,
			ves: 74,
			skils: {
				aggression: 16,
				anticipation: 12,
				bravery: 17,
				composure: 14,
				concentration: 14,
				decisions: 13,
				finishing: 15,
				flair: 8,
				of_the_ball: 16,
				positioning: 15,
				work_rate: 17,
				acceleration: 15,
				jumping: 16,
				pace: 16,
				stamina: 14,
				strength: 15,
				corners: 6,
				crossing: 5,
				dribbling: 13,
				first_touch: 11,
				free_kicks: 9,
				heading: 16,
				long_shots: 13,
				long_throws: 0,
				marking: 4,
				passing: 12,
				penalty: 17,
				tackling: 9,
				technique: 14,
				udar: 14
			}
		}
	]
}
;
// console.log(club1.squad[1]);

document.querySelector('#Pazzini > span').innerHTML = club2.squad[10].number;

document.querySelector('#goals_home').innerHTML = statsHome.goals;
document.querySelector('#goals_away').innerHTML = statsAway.goals;
document.querySelector('#shots').previousElementSibling.innerHTML = statsHome.shots;
document.querySelector('#shots_on_goals').previousElementSibling.innerHTML = statsAway.shots_on_goals;
document.querySelector('#possession').previousElementSibling.innerHTML = statsAway.possession;
document.querySelector('#passes').previousElementSibling.innerHTML = statsAway.passes;
document.querySelector('#crosses').previousElementSibling.innerHTML = statsAway.crosses;
document.querySelector('#free_kicks').previousElementSibling.innerHTML = statsAway.free_kicks;
document.querySelector('#corners').previousElementSibling.innerHTML = statsAway.corners;
document.querySelector('#fouls').previousElementSibling.innerHTML = statsAway.fouls;
document.querySelector('#yellow_cards').previousElementSibling.innerHTML = statsAway.yellow_cards;
document.querySelector('#red_cards').previousElementSibling.innerHTML = statsAway.red_cards;
document.querySelector('#tackles').previousElementSibling.innerHTML = statsAway.tackles;
document.querySelector('#dribbles').previousElementSibling.innerHTML = statsAway.dribbles;
document.querySelector('#offsides').previousElementSibling.innerHTML = statsAway.offsides;
document.querySelector('#shots').nextElementSibling.innerHTML = statsHome.shots;
document.querySelector('#shots_on_goals').nextElementSibling.innerHTML = statsAway.shots_on_goals;
document.querySelector('#possession').nextElementSibling.innerHTML = statsAway.possession;
document.querySelector('#passes').nextElementSibling.innerHTML = statsAway.passes;
document.querySelector('#crosses').nextElementSibling.innerHTML = statsAway.crosses;
document.querySelector('#free_kicks').nextElementSibling.innerHTML = statsAway.free_kicks;
document.querySelector('#corners').nextElementSibling.innerHTML = statsAway.corners;
document.querySelector('#fouls').nextElementSibling.innerHTML = statsAway.fouls;
document.querySelector('#yellow_cards').nextElementSibling.innerHTML = statsAway.yellow_cards;
document.querySelector('#red_cards').nextElementSibling.innerHTML = statsAway.red_cards;
document.querySelector('#tackles').nextElementSibling.innerHTML = statsAway.tackles;
document.querySelector('#dribbles').nextElementSibling.innerHTML = statsAway.dribbles;
document.querySelector('#offsides').nextElementSibling.innerHTML = statsAway.offsides;


play.onclick = function () {
	if (this.innerHTML == 'Играть') 
		this.innerHTML = 'Пауза';
	else 
		this.innerHTML = 'Играть';
};
